### ISSUE TITLE
复习line-height

### ISSUE THREAD

**Issue by Luna4** [Luna4/daily#22]
---

**line-height** [w3c][1]

> On a block container element whose content is composed of inline-level elements, 'line-height' specifies the minimal height of line boxes within the element.
On a non-replaced inline element, 'line-height' specifies the height that is used in the calculation of the line box height.

使用line-heigth一大特性点就是**垂直居中**

### Values

normal 
*Depends on the user agent. Desktop browsers (including Firefox) use a default value of roughly 1.2, depending on the element's font-family.//不仅与浏览器有关还会因字体不同计算后的line-height值会不一样*
```css
/* eg line-height的最终计算的值为21px*/
p {
    font-size:14px;
    line-height: 1.5;
}
```

number **推荐使用**
*The used value of the property is this number multiplied by the element's font size. Negative values are illegal.*
```css
/* eg line-height的最终计算的值为21px*/
p {
    font-size:14px;
    line-height: 1.5;
}
```
length
*The specified length is used in the calculation of the line box height.A length value can be defined using any valid CSS unit (px, em, rem, etc) Negative values are illegal.*

percentage
The computed value of the property is this percentage multiplied by the element's computed font size.
```css
p {
    font-size:14px;
}
.p1 {
    line-height:100%; /*14px*/
}
.p2 {
    line-height:200%; /*24px*/
}
```

inherit
Takes the same specified value as the property for the element's parent.

  [1]: http://www.w3.org/wiki/CSS/Properties/line-height
